/**
 * Popup controller for tab navigation and initialization
 */

document.addEventListener('DOMContentLoaded', () => {
    initializeTheme();
    initializeTabs();
    initializeOptionsButton();
    restoreActiveTab();
});

/**
 * Initialize theme system
 */
function initializeTheme() {
    // Load current theme from storage
    chrome.storage.local.get(['currentTheme', 'theme'], (result) => {
        const currentTheme = result.currentTheme || result.theme || 'classic';
        applyTheme(currentTheme);
    });

    // Listen for theme changes
    chrome.storage.onChanged.addListener((changes, namespace) => {
        if (namespace === 'local' && (changes.currentTheme || changes.theme)) {
            const newTheme = changes.currentTheme?.newValue || changes.theme?.newValue;
            if (newTheme) {
                applyTheme(newTheme);
            }
        }
    });
}

/**
 * Apply theme to popup
 */
function applyTheme(theme) {
    const themeConfig = getThemeConfig(theme);
    const root = document.documentElement;

    // Apply CSS custom properties
    Object.entries(themeConfig).forEach(([property, value]) => {
        root.style.setProperty(property, value);
    });

    // Set theme attribute for potential CSS selectors
    document.body.setAttribute('data-theme', theme);
}

/**
 * Get theme configuration
 */
function getThemeConfig(theme) {
    // Copy from theme-config.js
    const themes = {
        'classic': {
            '--theme-primary': '#667eea',
            '--theme-secondary': '#764ba2',
            '--theme-gradient': 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            '--theme-background': '#ffffff',
            '--theme-surface': '#ffffff',
            '--theme-surface-secondary': '#f5f5f5',
            '--theme-surface-tertiary': '#f9f9f9',
            '--theme-surface-hover': '#f0f0f0',
            '--theme-surface-active': '#e8e8e8',
            '--theme-surface-elevated': '#ffffff',
            '--theme-surface-modal': '#ffffff',
            '--theme-on-surface': '#333333',
            '--theme-on-surface-variant': '#666666',
            '--theme-on-surface-secondary': '#555555',
            '--theme-on-background': '#333333',
            '--theme-text-primary': '#333333',
            '--theme-text-secondary': '#666666',
            '--theme-text-tertiary': '#999999',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#aaaaaa',
            '--theme-border': '#e0e0e0',
            '--theme-border-variant': '#d1d1d6',
            '--theme-border-light': '#f0f0f0',
            '--theme-border-focus': '#667eea',
            '--theme-outline': '#e0e0e0',
            '--theme-outline-variant': '#f0f0f0',
            '--theme-accent': '#667eea',
            '--theme-accent-hover': '#5a6fd8',
            '--theme-accent-active': '#4c63d2',
            '--theme-accent-light': 'rgba(102, 126, 234, 0.1)',
            '--theme-tab-nav-bg': '#f5f5f5',
            '--theme-tab-hover': 'rgba(103, 58, 183, 0.05)',
            '--theme-tab-active-color': '#673ab7',
            '--theme-button-primary': '#667eea',
            '--theme-button-primary-hover': '#5a6fd8',
            '--theme-button-secondary': '#f5f5f5',
            '--theme-button-secondary-hover': '#e8e8e8',
            '--theme-input-background': '#ffffff',
            '--theme-input-border': '#e0e0e0',
            '--theme-input-focus': '#667eea',
            '--theme-card-background': '#ffffff',
            '--theme-card-border': '#e0e0e0',
            '--theme-list-item-background': '#ffffff',
            '--theme-list-item-hover': '#f5f5f5',
            '--theme-list-item-active': '#667eea',
            '--theme-shadow': '0 2px 8px rgba(0, 0, 0, 0.1)',
            '--theme-shadow-light': '0 1px 3px rgba(0, 0, 0, 0.1)',
            '--theme-shadow-medium': '0 2px 8px rgba(0, 0, 0, 0.15)',
            '--theme-shadow-heavy': '0 4px 16px rgba(0, 0, 0, 0.2)',
            '--theme-success': '#10b981',
            '--theme-warning': '#f59e0b',
            '--theme-error': '#ef4444',
            '--theme-info': '#3b82f6'
        },
        'classic-dark': {
            '--theme-primary': '#4a5568',
            '--theme-secondary': '#2d3748',
            '--theme-gradient': 'linear-gradient(135deg, #4a5568 0%, #2d3748 100%)',
            '--theme-background': '#1a202c',
            '--theme-surface': '#2d3748',
            '--theme-surface-secondary': '#4a5568',
            '--theme-surface-tertiary': '#374151',
            '--theme-surface-hover': '#374151',
            '--theme-surface-active': '#4a5568',
            '--theme-surface-elevated': '#2d3748',
            '--theme-surface-modal': '#2d3748',
            '--theme-on-surface': '#f7fafc',
            '--theme-on-surface-variant': '#e2e8f0',
            '--theme-on-surface-secondary': '#cbd5e0',
            '--theme-on-background': '#f7fafc',
            '--theme-text-primary': '#f7fafc',
            '--theme-text-secondary': '#e2e8f0',
            '--theme-text-tertiary': '#cbd5e0',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#a0aec0',
            '--theme-border': '#4a5568',
            '--theme-border-variant': '#374151',
            '--theme-border-light': '#4a5568',
            '--theme-border-focus': '#81c784',
            '--theme-outline': '#4a5568',
            '--theme-outline-variant': '#374151',
            '--theme-tab-nav-bg': '#4a5568',
            '--theme-tab-hover': 'rgba(160, 174, 192, 0.2)',
            '--theme-tab-active-color': '#81c784',
            '--theme-accent': '#81c784',
            '--theme-accent-hover': '#68b36b',
            '--theme-accent-active': '#5a9c5a',
            '--theme-accent-light': 'rgba(129, 199, 132, 0.2)',
            '--theme-button-primary': '#81c784',
            '--theme-button-primary-hover': '#68b36b',
            '--theme-button-secondary': '#4a5568',
            '--theme-button-secondary-hover': '#374151',
            '--theme-input-background': '#2d3748',
            '--theme-input-border': '#4a5568',
            '--theme-input-focus': '#81c784',
            '--theme-card-background': '#2d3748',
            '--theme-card-border': '#4a5568',
            '--theme-list-item-background': '#2d3748',
            '--theme-list-item-hover': '#374151',
            '--theme-list-item-active': '#81c784',
            '--theme-shadow': '0 2px 8px rgba(0, 0, 0, 0.3)',
            '--theme-shadow-light': '0 1px 3px rgba(0, 0, 0, 0.3)',
            '--theme-shadow-medium': '0 2px 8px rgba(0, 0, 0, 0.4)',
            '--theme-shadow-heavy': '0 4px 16px rgba(0, 0, 0, 0.5)',
            '--theme-success': '#68b36b',
            '--theme-warning': '#ed8936',
            '--theme-error': '#f56565',
            '--theme-info': '#63b3ed'
        },
        'gold': {
            '--theme-primary': '#B8860B',
            '--theme-secondary': '#DAA520',
            '--theme-gradient': 'linear-gradient(135deg, #B8860B 0%, #DAA520 100%)',
            '--theme-background': '#FFFDF7',
            '--theme-surface': '#ffffff',
            '--theme-surface-secondary': '#FAF8F0',
            '--theme-surface-tertiary': '#F7F3E9',
            '--theme-surface-hover': '#F0EBD8',
            '--theme-surface-active': '#E8DCC8',
            '--theme-surface-elevated': '#ffffff',
            '--theme-surface-modal': '#ffffff',
            '--theme-on-surface': '#1F1B13',
            '--theme-on-surface-variant': '#6B5B39',
            '--theme-on-surface-secondary': '#4A3F27',
            '--theme-on-background': '#1F1B13',
            '--theme-text-primary': '#1F1B13',
            '--theme-text-secondary': '#6B5B39',
            '--theme-text-tertiary': '#9A8B6B',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#C4B894',
            '--theme-border': '#E8DCC8',
            '--theme-border-variant': '#D4C5A9',
            '--theme-border-light': '#F0EBD8',
            '--theme-border-focus': '#B8860B',
            '--theme-outline': '#E8DCC8',
            '--theme-outline-variant': '#F0EBD8',
            '--theme-accent': '#B8860B',
            '--theme-accent-hover': '#9A7209',
            '--theme-accent-active': '#7D5F07',
            '--theme-accent-light': 'rgba(184, 134, 11, 0.1)',
            '--theme-tab-nav-bg': '#FAF8F0',
            '--theme-tab-hover': 'rgba(184, 134, 11, 0.1)',
            '--theme-tab-active-color': '#B8860B',
            '--theme-button-primary': '#B8860B',
            '--theme-button-primary-hover': '#9A7209',
            '--theme-button-secondary': '#FAF8F0',
            '--theme-button-secondary-hover': '#E8DCC8',
            '--theme-input-background': '#ffffff',
            '--theme-input-border': '#E8DCC8',
            '--theme-input-focus': '#B8860B',
            '--theme-card-background': '#ffffff',
            '--theme-card-border': '#E8DCC8',
            '--theme-list-item-background': '#ffffff',
            '--theme-list-item-hover': '#FAF8F0',
            '--theme-list-item-active': '#B8860B',
            '--theme-shadow': '0 2px 8px rgba(31, 27, 19, 0.1)',
            '--theme-shadow-light': '0 1px 3px rgba(31, 27, 19, 0.1)',
            '--theme-shadow-medium': '0 2px 8px rgba(31, 27, 19, 0.15)',
            '--theme-shadow-heavy': '0 4px 16px rgba(31, 27, 19, 0.2)',
            '--theme-success': '#22C55E',
            '--theme-warning': '#EAB308',
            '--theme-error': '#EF4444',
            '--theme-info': '#3B82F6'
        },
        'gold-dark': {
            '--theme-primary': '#8B6914',
            '--theme-secondary': '#6B4E00',
            '--theme-gradient': 'linear-gradient(135deg, #8B6914 0%, #6B4E00 100%)',
            '--theme-background': '#1A1611',
            '--theme-surface': '#2A2016',
            '--theme-surface-secondary': '#3A3026',
            '--theme-surface-tertiary': '#4A4439',
            '--theme-surface-hover': '#4A4439',
            '--theme-surface-active': '#3A3026',
            '--theme-surface-elevated': '#2A2016',
            '--theme-surface-modal': '#2A2016',
            '--theme-on-surface': '#E8E2D4',
            '--theme-on-surface-variant': '#B8B08A',
            '--theme-on-surface-secondary': '#A1916B',
            '--theme-on-background': '#E8E2D4',
            '--theme-text-primary': '#E8E2D4',
            '--theme-text-secondary': '#B8B08A',
            '--theme-text-tertiary': '#A1916B',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#8B7A5A',
            '--theme-border': '#4A4439',
            '--theme-border-variant': '#3A3026',
            '--theme-border-light': '#4A4439',
            '--theme-border-focus': '#FFDF9C',
            '--theme-outline': '#4A4439',
            '--theme-outline-variant': '#3A3026',
            '--theme-accent': '#FFDF9C',
            '--theme-accent-hover': '#E8C88C',
            '--theme-accent-active': '#D1B17C',
            '--theme-accent-light': 'rgba(255, 223, 156, 0.2)',
            '--theme-tab-nav-bg': '#3A3026',
            '--theme-tab-hover': 'rgba(139, 105, 20, 0.2)',
            '--theme-tab-active-color': '#FFDF9C',
            '--theme-button-primary': '#DAA520',
            '--theme-button-primary-hover': '#B8860B',
            '--theme-button-secondary': '#3A3026',
            '--theme-button-secondary-hover': '#4A4439',
            '--theme-input-background': '#2A2016',
            '--theme-input-border': '#4A4439',
            '--theme-input-focus': '#FFDF9C',
            '--theme-card-background': '#2A2016',
            '--theme-card-border': '#3A3026',
            '--theme-list-item-background': '#2A2016',
            '--theme-list-item-hover': '#3A3026',
            '--theme-list-item-active': '#DAA520',
            '--theme-shadow': '0 2px 8px rgba(0, 0, 0, 0.4)',
            '--theme-shadow-light': '0 1px 3px rgba(0, 0, 0, 0.4)',
            '--theme-shadow-medium': '0 2px 8px rgba(0, 0, 0, 0.5)',
            '--theme-shadow-heavy': '0 4px 16px rgba(0, 0, 0, 0.6)',
            '--theme-success': '#22C55E',
            '--theme-warning': '#EAB308',
            '--theme-error': '#EF4444',
            '--theme-info': '#3B82F6'
        },
        'platinum': {
            '--theme-primary': '#9CA3AF',
            '--theme-secondary': '#6B7280',
            '--theme-gradient': 'linear-gradient(135deg, #9CA3AF 0%, #6B7280 100%)',
            '--theme-background': '#FEFEFE',
            '--theme-surface': '#ffffff',
            '--theme-surface-secondary': '#F9FAFB',
            '--theme-surface-tertiary': '#F3F4F6',
            '--theme-surface-hover': '#F3F4F6',
            '--theme-surface-active': '#E5E7EB',
            '--theme-surface-elevated': '#ffffff',
            '--theme-surface-modal': '#ffffff',
            '--theme-on-surface': '#1A1A1A',
            '--theme-on-surface-variant': '#6B7280',
            '--theme-on-surface-secondary': '#4B5563',
            '--theme-on-background': '#1A1A1A',
            '--theme-text-primary': '#1A1A1A',
            '--theme-text-secondary': '#6B7280',
            '--theme-text-tertiary': '#9CA3AF',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#D1D5DB',
            '--theme-border': '#E5E7EB',
            '--theme-border-variant': '#D1D5DB',
            '--theme-border-light': '#F3F4F6',
            '--theme-border-focus': '#9CA3AF',
            '--theme-outline': '#E5E7EB',
            '--theme-outline-variant': '#F3F4F6',
            '--theme-accent': '#9CA3AF',
            '--theme-accent-hover': '#6B7280',
            '--theme-accent-active': '#4B5563',
            '--theme-accent-light': 'rgba(156, 163, 175, 0.1)',
            '--theme-tab-nav-bg': '#F9FAFB',
            '--theme-tab-hover': 'rgba(156, 163, 175, 0.1)',
            '--theme-tab-active-color': '#6B7280',
            '--theme-button-primary': '#9CA3AF',
            '--theme-button-primary-hover': '#6B7280',
            '--theme-button-secondary': '#F9FAFB',
            '--theme-button-secondary-hover': '#E5E7EB',
            '--theme-input-background': '#ffffff',
            '--theme-input-border': '#E5E7EB',
            '--theme-input-focus': '#9CA3AF',
            '--theme-card-background': '#ffffff',
            '--theme-card-border': '#E5E7EB',
            '--theme-list-item-background': '#ffffff',
            '--theme-list-item-hover': '#F9FAFB',
            '--theme-list-item-active': '#9CA3AF',
            '--theme-shadow': '0 2px 8px rgba(26, 26, 26, 0.1)',
            '--theme-shadow-light': '0 1px 3px rgba(26, 26, 26, 0.1)',
            '--theme-shadow-medium': '0 2px 8px rgba(26, 26, 26, 0.15)',
            '--theme-shadow-heavy': '0 4px 16px rgba(26, 26, 26, 0.2)',
            '--theme-success': '#22C55E',
            '--theme-warning': '#EAB308',
            '--theme-error': '#EF4444',
            '--theme-info': '#3B82F6'
        },
        'platinum-dark': {
            '--theme-primary': '#9CA3AF',
            '--theme-secondary': '#6B7280',
            '--theme-gradient': 'linear-gradient(135deg, #6B7280 0%, #4B5563 100%)',
            '--theme-background': '#121212',
            '--theme-surface': '#1F2937',
            '--theme-surface-secondary': '#374151',
            '--theme-surface-tertiary': '#475569',
            '--theme-surface-hover': '#475569',
            '--theme-surface-active': '#334155',
            '--theme-surface-elevated': '#1E293B',
            '--theme-surface-modal': '#1E293B',
            '--theme-on-surface': '#E8E8E8',
            '--theme-on-surface-variant': '#D1D5DB',
            '--theme-on-surface-secondary': '#94A3B8',
            '--theme-on-background': '#F1F5F9',
            '--theme-text-primary': '#F1F5F9',
            '--theme-text-secondary': '#CBD5E1',
            '--theme-text-tertiary': '#94A3B8',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#64748B',
            '--theme-border': '#475569',
            '--theme-border-variant': '#334155',
            '--theme-border-light': '#475569',
            '--theme-border-focus': '#93C5FD',
            '--theme-outline': '#475569',
            '--theme-outline-variant': '#334155',
            '--theme-accent': '#93C5FD',
            '--theme-accent-hover': '#60A5FA',
            '--theme-accent-active': '#3B82F6',
            '--theme-accent-light': 'rgba(147, 197, 253, 0.2)',
            '--theme-tab-nav-bg': '#334155',
            '--theme-tab-hover': 'rgba(59, 130, 246, 0.2)',
            '--theme-tab-active-color': '#93C5FD',
            '--theme-button-primary': '#3B82F6',
            '--theme-button-primary-hover': '#2563EB',
            '--theme-button-secondary': '#334155',
            '--theme-button-secondary-hover': '#475569',
            '--theme-input-background': '#1E293B',
            '--theme-input-border': '#475569',
            '--theme-input-focus': '#93C5FD',
            '--theme-card-background': '#1E293B',
            '--theme-card-border': '#334155',
            '--theme-list-item-background': '#1E293B',
            '--theme-list-item-hover': '#334155',
            '--theme-list-item-active': '#3B82F6',
            '--theme-shadow': '0 2px 8px rgba(0, 0, 0, 0.4)',
            '--theme-shadow-light': '0 1px 3px rgba(0, 0, 0, 0.4)',
            '--theme-shadow-medium': '0 2px 8px rgba(0, 0, 0, 0.5)',
            '--theme-shadow-heavy': '0 4px 16px rgba(0, 0, 0, 0.6)',
            '--theme-success': '#10B981',
            '--theme-warning': '#F59E0B',
            '--theme-error': '#EF4444',
            '--theme-info': '#3B82F6'
        },
        'emerald': {
            '--theme-primary': '#059669',
            '--theme-secondary': '#10B981',
            '--theme-gradient': 'linear-gradient(135deg, #059669 0%, #10B981 100%)',
            '--theme-background': '#F8FDF9',
            '--theme-surface': '#ffffff',
            '--theme-surface-secondary': '#F0FDF4',
            '--theme-surface-tertiary': '#ECFDF5',
            '--theme-surface-hover': '#ECFDF5',
            '--theme-surface-active': '#D1FAE5',
            '--theme-surface-elevated': '#ffffff',
            '--theme-surface-modal': '#ffffff',
            '--theme-on-surface': '#0F1B11',
            '--theme-on-surface-variant': '#166534',
            '--theme-on-surface-secondary': '#15803D',
            '--theme-on-background': '#0F1B11',
            '--theme-text-primary': '#0F1B11',
            '--theme-text-secondary': '#166534',
            '--theme-text-tertiary': '#15803D',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#A7F3D0',
            '--theme-border': '#D1FAE5',
            '--theme-border-variant': '#A7F3D0',
            '--theme-border-light': '#ECFDF5',
            '--theme-border-focus': '#059669',
            '--theme-outline': '#D1FAE5',
            '--theme-outline-variant': '#ECFDF5',
            '--theme-accent': '#059669',
            '--theme-accent-hover': '#047857',
            '--theme-accent-active': '#065F46',
            '--theme-accent-light': 'rgba(5, 150, 105, 0.1)',
            '--theme-tab-nav-bg': '#F0FDF4',
            '--theme-tab-hover': 'rgba(5, 150, 105, 0.1)',
            '--theme-tab-active-color': '#059669',
            '--theme-button-primary': '#059669',
            '--theme-button-primary-hover': '#047857',
            '--theme-button-secondary': '#F0FDF4',
            '--theme-button-secondary-hover': '#D1FAE5',
            '--theme-input-background': '#ffffff',
            '--theme-input-border': '#D1FAE5',
            '--theme-input-focus': '#059669',
            '--theme-card-background': '#ffffff',
            '--theme-card-border': '#D1FAE5',
            '--theme-list-item-background': '#ffffff',
            '--theme-list-item-hover': '#F0FDF4',
            '--theme-list-item-active': '#059669',
            '--theme-shadow': '0 2px 8px rgba(15, 27, 17, 0.1)',
            '--theme-shadow-light': '0 1px 3px rgba(15, 27, 17, 0.1)',
            '--theme-shadow-medium': '0 2px 8px rgba(15, 27, 17, 0.15)',
            '--theme-shadow-heavy': '0 4px 16px rgba(15, 27, 17, 0.2)',
            '--theme-success': '#22C55E',
            '--theme-warning': '#EAB308',
            '--theme-error': '#EF4444',
            '--theme-info': '#3B82F6'
        },
        'emerald-dark': {
            '--theme-primary': '#10B981',
            '--theme-secondary': '#065F46',
            '--theme-gradient': 'linear-gradient(135deg, #065F46 0%, #064E3B 100%)',
            '--theme-background': '#0A1A0C',
            '--theme-surface': '#1A2E1C',
            '--theme-surface-secondary': '#2A3E2C',
            '--theme-surface-tertiary': '#3A4E3C',
            '--theme-surface-hover': '#3A4E3C',
            '--theme-surface-active': '#2A3E2C',
            '--theme-surface-elevated': '#1A2E1C',
            '--theme-surface-modal': '#1A2E1C',
            '--theme-on-surface': '#D4E8D6',
            '--theme-on-surface-variant': '#A7F3D0',
            '--theme-on-surface-secondary': '#86EFAC',
            '--theme-on-background': '#D4E8D6',
            '--theme-text-primary': '#D4E8D6',
            '--theme-text-secondary': '#A7F3D0',
            '--theme-text-tertiary': '#86EFAC',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#6EE7B7',
            '--theme-border': '#374151',
            '--theme-border-variant': '#2A3E2C',
            '--theme-border-light': '#3A4E3C',
            '--theme-border-focus': '#6EE7B7',
            '--theme-outline': '#374151',
            '--theme-outline-variant': '#2A3E2C',
            '--theme-accent': '#6EE7B7',
            '--theme-accent-hover': '#10B981',
            '--theme-accent-active': '#059669',
            '--theme-accent-light': 'rgba(110, 231, 183, 0.2)',
            '--theme-tab-nav-bg': '#2A3E2C',
            '--theme-tab-hover': 'rgba(16, 185, 129, 0.2)',
            '--theme-tab-active-color': '#6EE7B7',
            '--theme-button-primary': '#10B981',
            '--theme-button-primary-hover': '#059669',
            '--theme-button-secondary': '#2A3E2C',
            '--theme-button-secondary-hover': '#3A4E3C',
            '--theme-input-background': '#1A2E1C',
            '--theme-input-border': '#374151',
            '--theme-input-focus': '#6EE7B7',
            '--theme-card-background': '#1A2E1C',
            '--theme-card-border': '#2A3E2C',
            '--theme-list-item-background': '#1A2E1C',
            '--theme-list-item-hover': '#2A3E2C',
            '--theme-list-item-active': '#10B981',
            '--theme-shadow': '0 2px 8px rgba(0, 0, 0, 0.4)',
            '--theme-shadow-light': '0 1px 3px rgba(0, 0, 0, 0.4)',
            '--theme-shadow-medium': '0 2px 8px rgba(0, 0, 0, 0.5)',
            '--theme-shadow-heavy': '0 4px 16px rgba(0, 0, 0, 0.6)',
            '--theme-success': '#22C55E',
            '--theme-warning': '#EAB308',
            '--theme-error': '#EF4444',
            '--theme-info': '#3B82F6'
        },
        'sapphire': {
            '--theme-primary': '#1E40AF',
            '--theme-secondary': '#3B82F6',
            '--theme-gradient': 'linear-gradient(135deg, #1E40AF 0%, #3B82F6 100%)',
            '--theme-background': '#F8FBFF',
            '--theme-surface': '#ffffff',
            '--theme-surface-secondary': '#EFF6FF',
            '--theme-surface-tertiary': '#F0F9FF',
            '--theme-surface-hover': '#F0F9FF',
            '--theme-surface-active': '#DBEAFE',
            '--theme-surface-elevated': '#ffffff',
            '--theme-surface-modal': '#ffffff',
            '--theme-on-surface': '#0F1419',
            '--theme-on-surface-variant': '#1E3A8A',
            '--theme-on-surface-secondary': '#1E40AF',
            '--theme-on-background': '#0F1419',
            '--theme-text-primary': '#0F1419',
            '--theme-text-secondary': '#1E3A8A',
            '--theme-text-tertiary': '#1E40AF',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#93C5FD',
            '--theme-border': '#DBEAFE',
            '--theme-border-variant': '#BFDBFE',
            '--theme-border-light': '#F0F9FF',
            '--theme-border-focus': '#1E40AF',
            '--theme-outline': '#DBEAFE',
            '--theme-outline-variant': '#F0F9FF',
            '--theme-accent': '#1E40AF',
            '--theme-accent-hover': '#1D4ED8',
            '--theme-accent-active': '#1E3A8A',
            '--theme-accent-light': 'rgba(30, 64, 175, 0.1)',
            '--theme-tab-nav-bg': '#EFF6FF',
            '--theme-tab-hover': 'rgba(30, 64, 175, 0.1)',
            '--theme-tab-active-color': '#1E40AF',
            '--theme-button-primary': '#1E40AF',
            '--theme-button-primary-hover': '#1D4ED8',
            '--theme-button-secondary': '#EFF6FF',
            '--theme-button-secondary-hover': '#DBEAFE',
            '--theme-input-background': '#ffffff',
            '--theme-input-border': '#DBEAFE',
            '--theme-input-focus': '#1E40AF',
            '--theme-card-background': '#ffffff',
            '--theme-card-border': '#DBEAFE',
            '--theme-list-item-background': '#ffffff',
            '--theme-list-item-hover': '#EFF6FF',
            '--theme-list-item-active': '#1E40AF',
            '--theme-shadow': '0 2px 8px rgba(15, 20, 25, 0.1)',
            '--theme-shadow-light': '0 1px 3px rgba(15, 20, 25, 0.1)',
            '--theme-shadow-medium': '0 2px 8px rgba(15, 20, 25, 0.15)',
            '--theme-shadow-heavy': '0 4px 16px rgba(15, 20, 25, 0.2)',
            '--theme-success': '#22C55E',
            '--theme-warning': '#EAB308',
            '--theme-error': '#EF4444',
            '--theme-info': '#3B82F6'
        },
        'sapphire-dark': {
            '--theme-primary': '#3B82F6',
            '--theme-secondary': '#1D4ED8',
            '--theme-gradient': 'linear-gradient(135deg, #1E3A8A 0%, #1D4ED8 100%)',
            '--theme-background': '#0F172A',
            '--theme-surface': '#1E293B',
            '--theme-surface-secondary': '#334155',
            '--theme-surface-tertiary': '#475569',
            '--theme-surface-hover': '#475569',
            '--theme-surface-active': '#334155',
            '--theme-surface-elevated': '#1E293B',
            '--theme-surface-modal': '#1E293B',
            '--theme-on-surface': '#F1F5F9',
            '--theme-on-surface-variant': '#CBD5E1',
            '--theme-on-surface-secondary': '#94A3B8',
            '--theme-on-background': '#F1F5F9',
            '--theme-text-primary': '#F1F5F9',
            '--theme-text-secondary': '#CBD5E1',
            '--theme-text-tertiary': '#94A3B8',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#64748B',
            '--theme-border': '#475569',
            '--theme-border-variant': '#334155',
            '--theme-border-light': '#475569',
            '--theme-border-focus': '#93C5FD',
            '--theme-outline': '#475569',
            '--theme-outline-variant': '#334155',
            '--theme-tab-nav-bg': '#334155',
            '--theme-tab-hover': 'rgba(59, 130, 246, 0.2)',
            '--theme-tab-active-color': '#93C5FD',
            '--theme-accent': '#93C5FD',
            '--theme-accent-hover': '#60A5FA',
            '--theme-accent-active': '#3B82F6',
            '--theme-accent-light': 'rgba(147, 197, 253, 0.2)',
            '--theme-button-primary': '#3B82F6',
            '--theme-button-primary-hover': '#2563EB',
            '--theme-button-secondary': '#334155',
            '--theme-button-secondary-hover': '#475569',
            '--theme-input-background': '#1E293B',
            '--theme-input-border': '#475569',
            '--theme-input-focus': '#93C5FD',
            '--theme-card-background': '#1E293B',
            '--theme-card-border': '#334155',
            '--theme-list-item-background': '#1E293B',
            '--theme-list-item-hover': '#334155',
            '--theme-list-item-active': '#3B82F6',
            '--theme-shadow': '0 2px 8px rgba(0, 0, 0, 0.4)',
            '--theme-shadow-light': '0 1px 3px rgba(0, 0, 0, 0.4)',
            '--theme-shadow-medium': '0 2px 8px rgba(0, 0, 0, 0.5)',
            '--theme-shadow-heavy': '0 4px 16px rgba(0, 0, 0, 0.6)',
            '--theme-success': '#10B981',
            '--theme-warning': '#F59E0B',
            '--theme-error': '#EF4444',
            '--theme-info': '#3B82F6'
        },
        'ruby': {
            '--theme-primary': '#DC2626',
            '--theme-secondary': '#EF4444',
            '--theme-gradient': 'linear-gradient(135deg, #DC2626 0%, #EF4444 100%)',
            '--theme-background': '#FFFBFB',
            '--theme-surface': '#ffffff',
            '--theme-surface-secondary': '#FEF2F2',
            '--theme-surface-tertiary': '#FEF7F7',
            '--theme-surface-hover': '#FEF7F7',
            '--theme-surface-active': '#FECACA',
            '--theme-surface-elevated': '#ffffff',
            '--theme-surface-modal': '#ffffff',
            '--theme-on-surface': '#1B0F0F',
            '--theme-on-surface-variant': '#991B1B',
            '--theme-on-surface-secondary': '#B91C1C',
            '--theme-on-background': '#1B0F0F',
            '--theme-text-primary': '#1B0F0F',
            '--theme-text-secondary': '#991B1B',
            '--theme-text-tertiary': '#B91C1C',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#FCA5A5',
            '--theme-border': '#FECACA',
            '--theme-border-variant': '#FCA5A5',
            '--theme-border-light': '#FEF7F7',
            '--theme-border-focus': '#DC2626',
            '--theme-outline': '#FECACA',
            '--theme-outline-variant': '#FEF7F7',
            '--theme-accent': '#DC2626',
            '--theme-accent-hover': '#B91C1C',
            '--theme-accent-active': '#991B1B',
            '--theme-accent-light': 'rgba(220, 38, 38, 0.1)',
            '--theme-tab-nav-bg': '#FEF2F2',
            '--theme-tab-hover': 'rgba(220, 38, 38, 0.1)',
            '--theme-tab-active-color': '#DC2626',
            '--theme-button-primary': '#DC2626',
            '--theme-button-primary-hover': '#B91C1C',
            '--theme-button-secondary': '#FEF2F2',
            '--theme-button-secondary-hover': '#FECACA',
            '--theme-input-background': '#ffffff',
            '--theme-input-border': '#FECACA',
            '--theme-input-focus': '#DC2626',
            '--theme-card-background': '#ffffff',
            '--theme-card-border': '#FECACA',
            '--theme-list-item-background': '#ffffff',
            '--theme-list-item-hover': '#FEF2F2',
            '--theme-list-item-active': '#DC2626',
            '--theme-shadow': '0 2px 8px rgba(27, 15, 15, 0.1)',
            '--theme-shadow-light': '0 1px 3px rgba(27, 15, 15, 0.1)',
            '--theme-shadow-medium': '0 2px 8px rgba(27, 15, 15, 0.15)',
            '--theme-shadow-heavy': '0 4px 16px rgba(27, 15, 15, 0.2)',
            '--theme-success': '#22C55E',
            '--theme-warning': '#EAB308',
            '--theme-error': '#EF4444',
            '--theme-info': '#3B82F6'
        },
        'ruby-dark': {
            '--theme-primary': '#EF4444',
            '--theme-secondary': '#991B1B',
            '--theme-gradient': 'linear-gradient(135deg, #7F1D1D 0%, #991B1B 100%)',
            '--theme-background': '#1A0A0A',
            '--theme-surface': '#2A1A1A',
            '--theme-surface-secondary': '#3A2A2A',
            '--theme-surface-tertiary': '#4A3A3A',
            '--theme-surface-hover': '#4A3A3A',
            '--theme-surface-active': '#3A2A2A',
            '--theme-surface-elevated': '#2A1A1A',
            '--theme-surface-modal': '#2A1A1A',
            '--theme-on-surface': '#E8D4D4',
            '--theme-on-surface-variant': '#FCA5A5',
            '--theme-on-surface-secondary': '#F87171',
            '--theme-on-background': '#E8D4D4',
            '--theme-text-primary': '#E8D4D4',
            '--theme-text-secondary': '#FCA5A5',
            '--theme-text-tertiary': '#F87171',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#EF4444',
            '--theme-border': '#991B1B',
            '--theme-border-variant': '#7F1D1D',
            '--theme-border-light': '#4A3A3A',
            '--theme-border-focus': '#FCA5A5',
            '--theme-outline': '#991B1B',
            '--theme-outline-variant': '#7F1D1D',
            '--theme-accent': '#FCA5A5',
            '--theme-accent-hover': '#EF4444',
            '--theme-accent-active': '#DC2626',
            '--theme-accent-light': 'rgba(252, 165, 165, 0.2)',
            '--theme-tab-nav-bg': '#3A2A2A',
            '--theme-tab-hover': 'rgba(239, 68, 68, 0.2)',
            '--theme-tab-active-color': '#FCA5A5',
            '--theme-button-primary': '#EF4444',
            '--theme-button-primary-hover': '#DC2626',
            '--theme-button-secondary': '#3A2A2A',
            '--theme-button-secondary-hover': '#4A3A3A',
            '--theme-input-background': '#2A1A1A',
            '--theme-input-border': '#991B1B',
            '--theme-input-focus': '#FCA5A5',
            '--theme-card-background': '#2A1A1A',
            '--theme-card-border': '#3A2A2A',
            '--theme-list-item-background': '#2A1A1A',
            '--theme-list-item-hover': '#3A2A2A',
            '--theme-list-item-active': '#EF4444',
            '--theme-shadow': '0 2px 8px rgba(0, 0, 0, 0.4)',
            '--theme-shadow-light': '0 1px 3px rgba(0, 0, 0, 0.4)',
            '--theme-shadow-medium': '0 2px 8px rgba(0, 0, 0, 0.5)',
            '--theme-shadow-heavy': '0 4px 16px rgba(0, 0, 0, 0.6)',
            '--theme-success': '#22C55E',
            '--theme-warning': '#EAB308',
            '--theme-error': '#EF4444',
            '--theme-info': '#3B82F6'
        },
        'amethyst': {
            '--theme-primary': '#7C3AED',
            '--theme-secondary': '#8B5CF6',
            '--theme-gradient': 'linear-gradient(135deg, #7C3AED 0%, #8B5CF6 100%)',
            '--theme-background': '#FDFBFF',
            '--theme-surface': '#ffffff',
            '--theme-surface-secondary': '#F5F3FF',
            '--theme-surface-tertiary': '#FAF5FF',
            '--theme-surface-hover': '#FAF5FF',
            '--theme-surface-active': '#E9D5FF',
            '--theme-surface-elevated': '#ffffff',
            '--theme-surface-modal': '#ffffff',
            '--theme-on-surface': '#1A0F1B',
            '--theme-on-surface-variant': '#5B21B6',
            '--theme-on-surface-secondary': '#6D28D9',
            '--theme-on-background': '#1A0F1B',
            '--theme-text-primary': '#1A0F1B',
            '--theme-text-secondary': '#5B21B6',
            '--theme-text-tertiary': '#6D28D9',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#C4B5FD',
            '--theme-border': '#E9D5FF',
            '--theme-border-variant': '#C4B5FD',
            '--theme-border-light': '#FAF5FF',
            '--theme-border-focus': '#7C3AED',
            '--theme-outline': '#E9D5FF',
            '--theme-outline-variant': '#FAF5FF',
            '--theme-accent': '#7C3AED',
            '--theme-accent-hover': '#6D28D9',
            '--theme-accent-active': '#5B21B6',
            '--theme-accent-light': 'rgba(124, 58, 237, 0.1)',
            '--theme-tab-nav-bg': '#F5F3FF',
            '--theme-tab-hover': 'rgba(124, 58, 237, 0.1)',
            '--theme-tab-active-color': '#7C3AED',
            '--theme-button-primary': '#7C3AED',
            '--theme-button-primary-hover': '#6D28D9',
            '--theme-button-secondary': '#F5F3FF',
            '--theme-button-secondary-hover': '#E9D5FF',
            '--theme-input-background': '#ffffff',
            '--theme-input-border': '#E9D5FF',
            '--theme-input-focus': '#7C3AED',
            '--theme-card-background': '#ffffff',
            '--theme-card-border': '#E9D5FF',
            '--theme-list-item-background': '#ffffff',
            '--theme-list-item-hover': '#F5F3FF',
            '--theme-list-item-active': '#7C3AED',
            '--theme-shadow': '0 2px 8px rgba(26, 15, 27, 0.1)',
            '--theme-shadow-light': '0 1px 3px rgba(26, 15, 27, 0.1)',
            '--theme-shadow-medium': '0 2px 8px rgba(26, 15, 27, 0.15)',
            '--theme-shadow-heavy': '0 4px 16px rgba(26, 15, 27, 0.2)',
            '--theme-success': '#22C55E',
            '--theme-warning': '#EAB308',
            '--theme-error': '#EF4444',
            '--theme-info': '#3B82F6'
        },
        'amethyst-dark': {
            '--theme-primary': '#8B5CF6',
            '--theme-secondary': '#6D28D9',
            '--theme-gradient': 'linear-gradient(135deg, #5B21B6 0%, #6D28D9 100%)',
            '--theme-background': '#1A0A1A',
            '--theme-surface': '#2A1A2A',
            '--theme-surface-secondary': '#3A2A3A',
            '--theme-surface-tertiary': '#4A3A4A',
            '--theme-surface-hover': '#4A3A4A',
            '--theme-surface-active': '#3A2A3A',
            '--theme-surface-elevated': '#2A1A2A',
            '--theme-surface-modal': '#2A1A2A',
            '--theme-on-surface': '#E8D4E8',
            '--theme-on-surface-variant': '#C4B5FD',
            '--theme-on-surface-secondary': '#A78BFA',
            '--theme-on-background': '#E8D4E8',
            '--theme-text-primary': '#E8D4E8',
            '--theme-text-secondary': '#C4B5FD',
            '--theme-text-tertiary': '#A78BFA',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#8B5CF6',
            '--theme-border': '#5B21B6',
            '--theme-border-variant': '#4C1D95',
            '--theme-border-light': '#4A3A4A',
            '--theme-border-focus': '#C4B5FD',
            '--theme-outline': '#5B21B6',
            '--theme-outline-variant': '#4C1D95',
            '--theme-accent': '#C4B5FD',
            '--theme-accent-hover': '#8B5CF6',
            '--theme-accent-active': '#7C3AED',
            '--theme-accent-light': 'rgba(196, 181, 253, 0.2)',
            '--theme-tab-nav-bg': '#3A2A3A',
            '--theme-tab-hover': 'rgba(139, 92, 246, 0.2)',
            '--theme-tab-active-color': '#C4B5FD',
            '--theme-button-primary': '#8B5CF6',
            '--theme-button-primary-hover': '#7C3AED',
            '--theme-button-secondary': '#3A2A3A',
            '--theme-button-secondary-hover': '#4A3A4A',
            '--theme-input-background': '#2A1A2A',
            '--theme-input-border': '#5B21B6',
            '--theme-input-focus': '#C4B5FD',
            '--theme-card-background': '#2A1A2A',
            '--theme-card-border': '#3A2A3A',
            '--theme-list-item-background': '#2A1A2A',
            '--theme-list-item-hover': '#3A2A3A',
            '--theme-list-item-active': '#8B5CF6',
            '--theme-shadow': '0 2px 8px rgba(0, 0, 0, 0.4)',
            '--theme-shadow-light': '0 1px 3px rgba(0, 0, 0, 0.4)',
            '--theme-shadow-medium': '0 2px 8px rgba(0, 0, 0, 0.5)',
            '--theme-shadow-heavy': '0 4px 16px rgba(0, 0, 0, 0.6)',
            '--theme-success': '#22C55E',
            '--theme-warning': '#EAB308',
            '--theme-error': '#EF4444',
            '--theme-info': '#3B82F6'
        },
        'copper': {
            '--theme-primary': '#C2410C',
            '--theme-secondary': '#EA580C',
            '--theme-gradient': 'linear-gradient(135deg, #C2410C 0%, #EA580C 100%)',
            '--theme-background': '#FFFCF9',
            '--theme-surface': '#ffffff',
            '--theme-surface-secondary': '#FFF7ED',
            '--theme-surface-tertiary': '#FEF3C7',
            '--theme-surface-hover': '#FEF3C7',
            '--theme-surface-active': '#FED7AA',
            '--theme-surface-elevated': '#ffffff',
            '--theme-surface-modal': '#ffffff',
            '--theme-on-surface': '#1B1611',
            '--theme-on-surface-variant': '#9A3412',
            '--theme-on-surface-secondary': '#B45309',
            '--theme-on-background': '#1B1611',
            '--theme-text-primary': '#1B1611',
            '--theme-text-secondary': '#9A3412',
            '--theme-text-tertiary': '#B45309',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#FDBA74',
            '--theme-border': '#FED7AA',
            '--theme-border-variant': '#FDBA74',
            '--theme-border-light': '#FEF3C7',
            '--theme-border-focus': '#C2410C',
            '--theme-outline': '#FED7AA',
            '--theme-outline-variant': '#FEF3C7',
            '--theme-accent': '#C2410C',
            '--theme-accent-hover': '#A16207',
            '--theme-accent-active': '#92400E',
            '--theme-accent-light': 'rgba(194, 65, 12, 0.1)',
            '--theme-tab-nav-bg': '#FFF7ED',
            '--theme-tab-hover': 'rgba(194, 65, 12, 0.1)',
            '--theme-tab-active-color': '#C2410C',
            '--theme-button-primary': '#C2410C',
            '--theme-button-primary-hover': '#A16207',
            '--theme-button-secondary': '#FFF7ED',
            '--theme-button-secondary-hover': '#FED7AA',
            '--theme-input-background': '#ffffff',
            '--theme-input-border': '#FED7AA',
            '--theme-input-focus': '#C2410C',
            '--theme-card-background': '#ffffff',
            '--theme-card-border': '#FED7AA',
            '--theme-list-item-background': '#ffffff',
            '--theme-list-item-hover': '#FFF7ED',
            '--theme-list-item-active': '#C2410C',
            '--theme-shadow': '0 2px 8px rgba(27, 22, 17, 0.1)',
            '--theme-shadow-light': '0 1px 3px rgba(27, 22, 17, 0.1)',
            '--theme-shadow-medium': '0 2px 8px rgba(27, 22, 17, 0.15)',
            '--theme-shadow-heavy': '0 4px 16px rgba(27, 22, 17, 0.2)',
            '--theme-success': '#22C55E',
            '--theme-warning': '#EAB308',
            '--theme-error': '#EF4444',
            '--theme-info': '#3B82F6'
        },
        'copper-dark': {
            '--theme-primary': '#EA580C',
            '--theme-secondary': '#9A3412',
            '--theme-gradient': 'linear-gradient(135deg, #7C2D12 0%, #9A3412 100%)',
            '--theme-background': '#1A1510',
            '--theme-surface': '#2A251A',
            '--theme-surface-secondary': '#3A352A',
            '--theme-surface-tertiary': '#4A453A',
            '--theme-surface-hover': '#4A453A',
            '--theme-surface-active': '#3A352A',
            '--theme-surface-elevated': '#2A251A',
            '--theme-surface-modal': '#2A251A',
            '--theme-on-surface': '#E8E0D4',
            '--theme-on-surface-variant': '#FDBA74',
            '--theme-on-surface-secondary': '#F59E0B',
            '--theme-on-background': '#E8E0D4',
            '--theme-text-primary': '#E8E0D4',
            '--theme-text-secondary': '#FDBA74',
            '--theme-text-tertiary': '#F59E0B',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#EA580C',
            '--theme-border': '#9A3412',
            '--theme-border-variant': '#7C2D12',
            '--theme-border-light': '#4A453A',
            '--theme-border-focus': '#FDBA74',
            '--theme-outline': '#9A3412',
            '--theme-outline-variant': '#7C2D12',
            '--theme-accent': '#FDBA74',
            '--theme-accent-hover': '#EA580C',
            '--theme-accent-active': '#C2410C',
            '--theme-accent-light': 'rgba(253, 186, 116, 0.2)',
            '--theme-tab-nav-bg': '#3A352A',
            '--theme-tab-hover': 'rgba(234, 88, 12, 0.2)',
            '--theme-tab-active-color': '#FDBA74',
            '--theme-button-primary': '#EA580C',
            '--theme-button-primary-hover': '#C2410C',
            '--theme-button-secondary': '#3A352A',
            '--theme-button-secondary-hover': '#4A453A',
            '--theme-input-background': '#2A251A',
            '--theme-input-border': '#9A3412',
            '--theme-input-focus': '#FDBA74',
            '--theme-card-background': '#2A251A',
            '--theme-card-border': '#3A352A',
            '--theme-list-item-background': '#2A251A',
            '--theme-list-item-hover': '#3A352A',
            '--theme-list-item-active': '#EA580C',
            '--theme-shadow': '0 2px 8px rgba(0, 0, 0, 0.4)',
            '--theme-shadow-light': '0 1px 3px rgba(0, 0, 0, 0.4)',
            '--theme-shadow-medium': '0 2px 8px rgba(0, 0, 0, 0.5)',
            '--theme-shadow-heavy': '0 4px 16px rgba(0, 0, 0, 0.6)',
            '--theme-success': '#22C55E',
            '--theme-warning': '#EAB308',
            '--theme-error': '#EF4444',
            '--theme-info': '#3B82F6'
        },
        'obsidian': {
            '--theme-primary': '#374151',
            '--theme-secondary': '#000000',
            '--theme-gradient': 'linear-gradient(135deg, #000000 0%, #374151 100%)',
            '--theme-background': '#FFFFFF',
            '--theme-surface': '#ffffff',
            '--theme-surface-secondary': '#F9FAFB',
            '--theme-surface-tertiary': '#F3F4F6',
            '--theme-surface-hover': '#F3F4F6',
            '--theme-surface-active': '#E5E7EB',
            '--theme-surface-elevated': '#ffffff',
            '--theme-surface-modal': '#ffffff',
            '--theme-on-surface': '#000000',
            '--theme-on-surface-variant': '#374151',
            '--theme-on-surface-secondary': '#6B7280',
            '--theme-on-background': '#000000',
            '--theme-text-primary': '#000000',
            '--theme-text-secondary': '#374151',
            '--theme-text-tertiary': '#6B7280',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#9CA3AF',
            '--theme-border': '#E5E7EB',
            '--theme-border-variant': '#D1D5DB',
            '--theme-border-light': '#F3F4F6',
            '--theme-border-focus': '#374151',
            '--theme-outline': '#E5E7EB',
            '--theme-outline-variant': '#F3F4F6',
            '--theme-accent': '#374151',
            '--theme-accent-hover': '#1F2937',
            '--theme-accent-active': '#111827',
            '--theme-accent-light': 'rgba(55, 65, 81, 0.1)',
            '--theme-tab-nav-bg': '#F9FAFB',
            '--theme-tab-hover': 'rgba(55, 65, 81, 0.1)',
            '--theme-tab-active-color': '#000000',
            '--theme-button-primary': '#374151',
            '--theme-button-primary-hover': '#1F2937',
            '--theme-button-secondary': '#F9FAFB',
            '--theme-button-secondary-hover': '#E5E7EB',
            '--theme-input-background': '#ffffff',
            '--theme-input-border': '#E5E7EB',
            '--theme-input-focus': '#374151',
            '--theme-card-background': '#ffffff',
            '--theme-card-border': '#E5E7EB',
            '--theme-list-item-background': '#ffffff',
            '--theme-list-item-hover': '#F9FAFB',
            '--theme-list-item-active': '#374151',
            '--theme-shadow': '0 2px 8px rgba(0, 0, 0, 0.1)',
            '--theme-shadow-light': '0 1px 3px rgba(0, 0, 0, 0.1)',
            '--theme-shadow-medium': '0 2px 8px rgba(0, 0, 0, 0.15)',
            '--theme-shadow-heavy': '0 4px 16px rgba(0, 0, 0, 0.2)',
            '--theme-success': '#22C55E',
            '--theme-warning': '#EAB308',
            '--theme-error': '#EF4444',
            '--theme-info': '#3B82F6'
        },
        'obsidian-dark': {
            '--theme-primary': '#6B7280',
            '--theme-secondary': '#374151',
            '--theme-gradient': 'linear-gradient(135deg, #000000 0%, #111827 100%)',
            '--theme-background': '#000000',
            '--theme-surface': '#111827',
            '--theme-surface-secondary': '#1F2937',
            '--theme-surface-tertiary': '#374151',
            '--theme-surface-hover': '#374151',
            '--theme-surface-active': '#1F2937',
            '--theme-surface-elevated': '#111827',
            '--theme-surface-modal': '#111827',
            '--theme-on-surface': '#FFFFFF',
            '--theme-on-surface-variant': '#D1D5DB',
            '--theme-on-surface-secondary': '#9CA3AF',
            '--theme-on-background': '#FFFFFF',
            '--theme-text-primary': '#FFFFFF',
            '--theme-text-secondary': '#D1D5DB',
            '--theme-text-tertiary': '#9CA3AF',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#6B7280',
            '--theme-border': '#374151',
            '--theme-border-variant': '#1F2937',
            '--theme-border-light': '#374151',
            '--theme-border-focus': '#6B7280',
            '--theme-outline': '#374151',
            '--theme-outline-variant': '#1F2937',
            '--theme-accent': '#6B7280',
            '--theme-accent-hover': '#9CA3AF',
            '--theme-accent-active': '#D1D5DB',
            '--theme-accent-light': 'rgba(107, 114, 128, 0.2)',
            '--theme-tab-nav-bg': '#1F2937',
            '--theme-tab-hover': 'rgba(107, 114, 128, 0.2)',
            '--theme-tab-active-color': '#FFFFFF',
            '--theme-button-primary': '#6B7280',
            '--theme-button-primary-hover': '#9CA3AF',
            '--theme-button-secondary': '#1F2937',
            '--theme-button-secondary-hover': '#374151',
            '--theme-input-background': '#111827',
            '--theme-input-border': '#374151',
            '--theme-input-focus': '#6B7280',
            '--theme-card-background': '#111827',
            '--theme-card-border': '#1F2937',
            '--theme-list-item-background': '#111827',
            '--theme-list-item-hover': '#1F2937',
            '--theme-list-item-active': '#6B7280',
            '--theme-shadow': '0 2px 8px rgba(0, 0, 0, 0.4)',
            '--theme-shadow-light': '0 1px 3px rgba(0, 0, 0, 0.4)',
            '--theme-shadow-medium': '0 2px 8px rgba(0, 0, 0, 0.5)',
            '--theme-shadow-heavy': '0 4px 16px rgba(0, 0, 0, 0.6)',
            '--theme-success': '#22C55E',
            '--theme-warning': '#EAB308',
            '--theme-error': '#EF4444',
            '--theme-info': '#3B82F6'
        },
        'steel': {
            '--theme-primary': '#475569',
            '--theme-secondary': '#64748B',
            '--theme-gradient': 'linear-gradient(135deg, #475569 0%, #64748B 100%)',
            '--theme-background': '#F8FAFC',
            '--theme-surface': '#ffffff',
            '--theme-surface-secondary': '#F1F5F9',
            '--theme-surface-tertiary': '#E2E8F0',
            '--theme-surface-hover': '#E2E8F0',
            '--theme-surface-active': '#CBD5E1',
            '--theme-surface-elevated': '#ffffff',
            '--theme-surface-modal': '#ffffff',
            '--theme-on-surface': '#1E293B',
            '--theme-on-surface-variant': '#475569',
            '--theme-on-surface-secondary': '#64748B',
            '--theme-on-background': '#1E293B',
            '--theme-text-primary': '#1E293B',
            '--theme-text-secondary': '#475569',
            '--theme-text-tertiary': '#64748B',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#94A3B8',
            '--theme-border': '#E2E8F0',
            '--theme-border-variant': '#CBD5E1',
            '--theme-border-light': '#E2E8F0',
            '--theme-border-focus': '#475569',
            '--theme-outline': '#E2E8F0',
            '--theme-outline-variant': '#CBD5E1',
            '--theme-accent': '#475569',
            '--theme-accent-hover': '#334155',
            '--theme-accent-active': '#1E293B',
            '--theme-accent-light': 'rgba(71, 85, 105, 0.1)',
            '--theme-tab-nav-bg': '#F1F5F9',
            '--theme-tab-hover': 'rgba(71, 85, 105, 0.1)',
            '--theme-tab-active-color': '#475569',
            '--theme-button-primary': '#475569',
            '--theme-button-primary-hover': '#334155',
            '--theme-button-secondary': '#F1F5F9',
            '--theme-button-secondary-hover': '#E2E8F0',
            '--theme-input-background': '#ffffff',
            '--theme-input-border': '#E2E8F0',
            '--theme-input-focus': '#475569',
            '--theme-card-background': '#ffffff',
            '--theme-card-border': '#E2E8F0',
            '--theme-list-item-background': '#ffffff',
            '--theme-list-item-hover': '#F1F5F9',
            '--theme-list-item-active': '#475569',
            '--theme-shadow': '0 2px 8px rgba(30, 41, 59, 0.1)',
            '--theme-shadow-light': '0 1px 3px rgba(30, 41, 59, 0.1)',
            '--theme-shadow-medium': '0 2px 8px rgba(30, 41, 59, 0.15)',
            '--theme-shadow-heavy': '0 4px 16px rgba(30, 41, 59, 0.2)',
            '--theme-success': '#22C55E',
            '--theme-warning': '#EAB308',
            '--theme-error': '#EF4444',
            '--theme-info': '#3B82F6'
        },
        'steel-dark': {
            '--theme-primary': '#64748B',
            '--theme-secondary': '#475569',
            '--theme-gradient': 'linear-gradient(135deg, #0F172A 0%, #334155 100%)',
            '--theme-background': '#0F172A',
            '--theme-surface': '#1E293B',
            '--theme-surface-secondary': '#334155',
            '--theme-surface-tertiary': '#475569',
            '--theme-surface-hover': '#475569',
            '--theme-surface-active': '#334155',
            '--theme-surface-elevated': '#1E293B',
            '--theme-surface-modal': '#1E293B',
            '--theme-on-surface': '#E2E8F0',
            '--theme-on-surface-variant': '#CBD5E1',
            '--theme-on-surface-secondary': '#94A3B8',
            '--theme-on-background': '#E2E8F0',
            '--theme-text-primary': '#E2E8F0',
            '--theme-text-secondary': '#CBD5E1',
            '--theme-text-tertiary': '#94A3B8',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#64748B',
            '--theme-border': '#475569',
            '--theme-border-variant': '#334155',
            '--theme-border-light': '#475569',
            '--theme-border-focus': '#64748B',
            '--theme-outline': '#475569',
            '--theme-outline-variant': '#334155',
            '--theme-accent': '#64748B',
            '--theme-accent-hover': '#94A3B8',
            '--theme-accent-active': '#CBD5E1',
            '--theme-accent-light': 'rgba(100, 116, 139, 0.2)',
            '--theme-tab-nav-bg': '#334155',
            '--theme-tab-hover': 'rgba(100, 116, 139, 0.2)',
            '--theme-tab-active-color': '#CBD5E1',
            '--theme-button-primary': '#64748B',
            '--theme-button-primary-hover': '#94A3B8',
            '--theme-button-secondary': '#334155',
            '--theme-button-secondary-hover': '#475569',
            '--theme-input-background': '#1E293B',
            '--theme-input-border': '#475569',
            '--theme-input-focus': '#64748B',
            '--theme-card-background': '#1E293B',
            '--theme-card-border': '#334155',
            '--theme-list-item-background': '#1E293B',
            '--theme-list-item-hover': '#334155',
            '--theme-list-item-active': '#64748B',
            '--theme-shadow': '0 2px 8px rgba(0, 0, 0, 0.4)',
            '--theme-shadow-light': '0 1px 3px rgba(0, 0, 0, 0.4)',
            '--theme-shadow-medium': '0 2px 8px rgba(0, 0, 0, 0.5)',
            '--theme-shadow-heavy': '0 4px 16px rgba(0, 0, 0, 0.6)',
            '--theme-success': '#22C55E',
            '--theme-warning': '#EAB308',
            '--theme-error': '#EF4444',
            '--theme-info': '#3B82F6'
        },
        'midnight': {
            '--theme-primary': '#1E1B4B',
            '--theme-secondary': '#312E81',
            '--theme-gradient': 'linear-gradient(135deg, #1E1B4B 0%, #312E81 100%)',
            '--theme-background': '#FAFBFF',
            '--theme-surface': '#ffffff',
            '--theme-surface-secondary': '#F0F4FF',
            '--theme-surface-tertiary': '#E0E7FF',
            '--theme-surface-hover': '#E0E7FF',
            '--theme-surface-active': '#C7D2FE',
            '--theme-surface-elevated': '#ffffff',
            '--theme-surface-modal': '#ffffff',
            '--theme-on-surface': '#0A0E1A',
            '--theme-on-surface-variant': '#1E1B4B',
            '--theme-on-surface-secondary': '#312E81',
            '--theme-on-background': '#0A0E1A',
            '--theme-text-primary': '#0A0E1A',
            '--theme-text-secondary': '#1E1B4B',
            '--theme-text-tertiary': '#312E81',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#A5B4FC',
            '--theme-border': '#E0E7FF',
            '--theme-border-variant': '#C7D2FE',
            '--theme-border-light': '#E0E7FF',
            '--theme-border-focus': '#1E1B4B',
            '--theme-outline': '#E0E7FF',
            '--theme-outline-variant': '#C7D2FE',
            '--theme-accent': '#1E1B4B',
            '--theme-accent-hover': '#312E81',
            '--theme-accent-active': '#4338CA',
            '--theme-accent-light': 'rgba(30, 27, 75, 0.1)',
            '--theme-tab-nav-bg': '#F0F4FF',
            '--theme-tab-hover': 'rgba(30, 27, 75, 0.1)',
            '--theme-tab-active-color': '#1E1B4B',
            '--theme-button-primary': '#1E1B4B',
            '--theme-button-primary-hover': '#312E81',
            '--theme-button-secondary': '#F0F4FF',
            '--theme-button-secondary-hover': '#E0E7FF',
            '--theme-input-background': '#ffffff',
            '--theme-input-border': '#E0E7FF',
            '--theme-input-focus': '#1E1B4B',
            '--theme-card-background': '#ffffff',
            '--theme-card-border': '#E0E7FF',
            '--theme-list-item-background': '#ffffff',
            '--theme-list-item-hover': '#F0F4FF',
            '--theme-list-item-active': '#1E1B4B',
            '--theme-shadow': '0 2px 8px rgba(10, 14, 26, 0.1)',
            '--theme-shadow-light': '0 1px 3px rgba(10, 14, 26, 0.1)',
            '--theme-shadow-medium': '0 2px 8px rgba(10, 14, 26, 0.15)',
            '--theme-shadow-heavy': '0 4px 16px rgba(10, 14, 26, 0.2)',
            '--theme-success': '#22C55E',
            '--theme-warning': '#EAB308',
            '--theme-error': '#EF4444',
            '--theme-info': '#3B82F6'
        },
        'midnight-dark': {
            '--theme-primary': '#6366F1',
            '--theme-secondary': '#312E81',
            '--theme-gradient': 'linear-gradient(135deg, #000510 0%, #1A1625 100%)',
            '--theme-background': '#000510',
            '--theme-surface': '#0A0A1A',
            '--theme-surface-secondary': '#1A1625',
            '--theme-surface-tertiary': '#2A2635',
            '--theme-surface-hover': '#2A2635',
            '--theme-surface-active': '#1A1625',
            '--theme-surface-elevated': '#0A0A1A',
            '--theme-surface-modal': '#0A0A1A',
            '--theme-on-surface': '#E6F0FF',
            '--theme-on-surface-variant': '#A5B4FC',
            '--theme-on-surface-secondary': '#818CF8',
            '--theme-on-background': '#E6F0FF',
            '--theme-text-primary': '#E6F0FF',
            '--theme-text-secondary': '#A5B4FC',
            '--theme-text-tertiary': '#818CF8',
            '--theme-text-on-gradient': '#ffffff',
            '--theme-text-muted': '#6366F1',
            '--theme-border': '#312E81',
            '--theme-border-variant': '#1E1B4B',
            '--theme-border-light': '#2A2635',
            '--theme-border-focus': '#A5B4FC',
            '--theme-outline': '#312E81',
            '--theme-outline-variant': '#1E1B4B',
            '--theme-accent': '#A5B4FC',
            '--theme-accent-hover': '#6366F1',
            '--theme-accent-active': '#4F46E5',
            '--theme-accent-light': 'rgba(165, 180, 252, 0.2)',
            '--theme-tab-nav-bg': '#1A1625',
            '--theme-tab-hover': 'rgba(99, 102, 241, 0.2)',
            '--theme-tab-active-color': '#A5B4FC',
            '--theme-button-primary': '#6366F1',
            '--theme-button-primary-hover': '#4F46E5',
            '--theme-button-secondary': '#1A1625',
            '--theme-button-secondary-hover': '#2A2635',
            '--theme-input-background': '#0A0A1A',
            '--theme-input-border': '#312E81',
            '--theme-input-focus': '#A5B4FC',
            '--theme-card-background': '#0A0A1A',
            '--theme-card-border': '#1A1625',
            '--theme-list-item-background': '#0A0A1A',
            '--theme-list-item-hover': '#1A1625',
            '--theme-list-item-active': '#6366F1',
            '--theme-shadow': '0 2px 8px rgba(0, 0, 0, 0.4)',
            '--theme-shadow-light': '0 1px 3px rgba(0, 0, 0, 0.4)',
            '--theme-shadow-medium': '0 2px 8px rgba(0, 0, 0, 0.5)',
            '--theme-shadow-heavy': '0 4px 16px rgba(0, 0, 0, 0.6)',
            '--theme-success': '#22C55E',
            '--theme-warning': '#EAB308',
            '--theme-error': '#EF4444',
            '--theme-info': '#3B82F6'
        }
    };

    return themes[theme] || themes.classic;
}

/**
 * Initialize tab navigation functionality
 */
function initializeTabs() {
    const tabButtons = document.querySelectorAll('.tab-button');
    const tabPanes = document.querySelectorAll('.tab-pane');

    tabButtons.forEach(button => {
        button.addEventListener('click', () => {
            const targetTab = button.dataset.tab;

            // Update button states
            tabButtons.forEach(btn => btn.classList.remove('active'));
            button.classList.add('active');

            // Update pane visibility
            tabPanes.forEach(pane => {
                if (pane.id === targetTab) {
                    pane.classList.add('active');
                } else {
                    pane.classList.remove('active');
                }
            });

            // Save active tab to storage
            chrome.storage.local.set({ activeTab: targetTab });

            // Trigger resize event for proper rendering
            window.dispatchEvent(new Event('resize'));
        });
    });
}

/**
 * Initialize options button functionality
 */
function initializeOptionsButton() {
    const optionsButton = document.getElementById('options-button');
    if (optionsButton) {
        optionsButton.addEventListener('click', () => {
            chrome.tabs.create({
                url: chrome.runtime.getURL('options.html')
            });
        });
    }
}

/**
 * Restore the last active tab from storage
 */
function restoreActiveTab() {
    chrome.storage.local.get(['activeTab'], (result) => {
        if (result.activeTab) {
            const tabButton = document.querySelector(`[data-tab="${result.activeTab}"]`);
            if (tabButton) {
                tabButton.click();
            }
        }
    });
}
